import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import * as telemetryService from "../../services/api/telemetryService";
import type { TelemetrySeriesResponse } from "../../types";
import { formatTelemetryNumber, formatTelemetryTimestamp, humanizeMetricKey, stableSeriesColor } from "../telemetry-explorer/metricPresentation";
import { ErrorState, LoadingState } from "../feedback/FeedbackStates";
import { type OperationalPeriod, summarizeSeries, timeWindow } from "./operationalMetrics";

const preferred = ["gateway.cpu_temperature_c","gateway.load_1m","gateway.memory_used_percent","gateway.disk_used_percent","gateway.queue_depth","environment.temperature_c","environment.humidity_percent"];
const labels:Record<string,string>={"gateway.cpu_temperature_c":"Temperatura da CPU","gateway.load_1m":"Carga do sistema","gateway.memory_used_percent":"Memória","gateway.disk_used_percent":"Disco","gateway.queue_depth":"Fila local","environment.temperature_c":"Temperatura ambiente","environment.humidity_percent":"Umidade"};
const units:Record<string,string>={"gateway.cpu_temperature_c":"°C","gateway.memory_used_percent":"%","gateway.disk_used_percent":"%","gateway.queue_depth":"mensagens","environment.temperature_c":"°C","environment.humidity_percent":"%"};

export function OperationalHistory({token,workspaceId,deviceId,availableKeys}:{token:string;workspaceId:string;deviceId:string;availableKeys:string[]}){
 const metricKeys=useMemo(()=>preferred.filter(key=>availableKeys.includes(key)),[availableKeys]);
 const [period,setPeriod]=useState<OperationalPeriod>("6h"),[series,setSeries]=useState<TelemetrySeriesResponse[]>([]),[active,setActive]=useState<string[]>(metricKeys),[loading,setLoading]=useState(false),[error,setError]=useState<unknown>(null);
 useEffect(()=>setActive(metricKeys),[metricKeys]);
 useEffect(()=>{if(!metricKeys.length)return;let mounted=true;const range=timeWindow(period);setLoading(true);setError(null);telemetryService.queryTelemetry(token,workspaceId,{deviceIds:[deviceId],metricKeys,fromUtc:range.fromUtc,toUtc:range.toUtc,aggregation:"raw",bucket:null}).then(r=>{if(mounted)setSeries(r.series.filter(s=>s.valueType==="Numeric"))}).catch(e=>{if(mounted)setError(e)}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[token,workspaceId,deviceId,period,metricKeys]);
 function choose(key:string,combine:boolean){if(!combine){setActive(current=>current.length===1&&current[0]===key?series.map(s=>s.metricKey):[key]);return}setActive(current=>current.includes(key)?current.filter(x=>x!==key):[...current,key]);}
 if(!metricKeys.length)return null;
 return <section className="panel operational-history"><div className="operational-history-header"><div><p className="dashboard-card-eyebrow">Histórico</p><h2>Comportamento nas últimas {period.replace("h"," horas")}</h2><p>As faixas compartilham o mesmo período e preservam a escala e a unidade de cada métrica.</p></div><div className="range-selector" role="group" aria-label="Período do histórico">{(["1h","6h","24h"] as OperationalPeriod[]).map(value=><button key={value} type="button" aria-pressed={period===value} onClick={()=>setPeriod(value)}>{value}</button>)}</div></div>
 {loading?<LoadingState compact title="Consultando histórico"/>:null}{error?<ErrorState compact title="Não foi possível consultar o histórico" description="Os valores atuais continuam disponíveis acima."/>:null}
 {!loading&&!error&&series.length?<><div className="operational-legend"><button type="button" onClick={()=>setActive(series.map(s=>s.metricKey))}>Ver tudo</button>{series.map(s=><button key={s.metricKey} type="button" aria-pressed={active.includes(s.metricKey)} style={{"--series-color":stableSeriesColor(s.metricKey)} as React.CSSProperties} onClick={event=>choose(s.metricKey,event.ctrlKey||event.shiftKey)}>{labels[s.metricKey]??humanizeMetricKey(s.metricKey)}</button>)}</div><p className="interaction-hint">Clique para isolar; use Ctrl ou Shift para combinar métricas.</p><div className="small-multiples">{series.filter(s=>active.includes(s.metricKey)).map(s=><MetricStrip key={s.metricKey} series={s}/>)}</div></>:null}
 </section>
}
function MetricStrip({series}:{series:TelemetrySeriesResponse}){const summary=summarizeSeries(series),unit=series.canonicalUnit||units[series.metricKey]||"",data=series.points.map(p=>({timestamp:p.timestampUtc,value:p.numericValue}));return <article className="metric-strip"><header><div><h3>{labels[series.metricKey]??humanizeMetricKey(series.metricKey)}</h3><code>{series.metricKey}</code></div>{summary?<p><strong>{formatTelemetryNumber(summary.current)} {unit}</strong><span>mín. {formatTelemetryNumber(summary.min)} · máx. {formatTelemetryNumber(summary.max)} · {summary.trend}</span></p>:null}</header><div className="metric-strip-chart" role="img" aria-label={(labels[series.metricKey]??series.metricKey)+": "+(summary?summary.trend:"sem dados")}><ResponsiveContainer width="100%" height={120}><LineChart data={data} margin={{top:8,right:12,bottom:4,left:4}}><CartesianGrid vertical={false} stroke="var(--color-border)" strokeDasharray="3 3"/><XAxis dataKey="timestamp" tickFormatter={v=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(new Date(String(v)))} minTickGap={40} tick={{fontSize:11}}/><YAxis width={50} domain={["auto","auto"]} tickFormatter={formatTelemetryNumber} tick={{fontSize:11}}/><Tooltip labelFormatter={v=>formatTelemetryTimestamp(String(v))} formatter={v=>[formatTelemetryNumber(Number(v))+" "+unit,labels[series.metricKey]??series.metricKey]}/><Line dataKey="value" type="monotone" stroke={stableSeriesColor(series.metricKey)} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></article>}
