// <auto-generated />
using System;
using Fluxo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluxo.Infrastructure.Migrations
{
    [DbContext(typeof(FluxoDbContext))]
    [Migration("20260906225556_AddAlertBackend")]
    partial class AddAlertBackend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId", "AuthorId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "EventId");

                    b.ToTable("alert_acknowledgements", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertDeliveryIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("TransitionId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "TransitionId");

                    b.ToTable("alert_delivery_intents", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertDeviceCoordination", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("NextOrder")
                        .HasColumnType("bigint");

                    b.HasKey("WorkspaceId", "DeviceIdentifier");

                    b.ToTable("alert_device_coordination", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvaluationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("QueueOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("Status", "NextAttemptAtUtc", "LeaseUntilUtc");

                    b.HasIndex("WorkItemId", "RuleId", "RevisionId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "RuleId", "RevisionId");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier", "QueueOrder", "WorkItemId");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier", "RuleId", "QueueOrder");

                    b.ToTable("alert_evaluation_attempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_alert_attempt_status", "\"Status\" IN ('Pending','Claimed','Completed','Failed','DeadLetter','Skipped')");
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvaluationWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("IngestionRecordId")
                        .HasColumnType("uuid");

                    b.Property<long>("QueueOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "IngestionRecordId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "DeviceIdentifier", "IngestionRecordId");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier", "QueueOrder")
                        .IsUnique();

                    b.ToTable("alert_evaluation_work_items", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TriggeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier");

                    b.HasIndex("WorkspaceId", "RuleId", "DeviceIdentifier")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Firing'");

                    b.HasIndex("WorkspaceId", "RuleId", "RevisionId");

                    b.ToTable("alert_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_alert_event_status", "\"Status\" IN ('Firing','Resolved','Closed')");
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEventTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IngestionRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "EventId");

                    b.HasIndex("WorkspaceId", "IngestionRecordId");

                    b.ToTable("alert_event_transitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_alert_transition_kind", "\"Kind\" IN ('Firing','Resolved','Closed')");
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Id", "CurrentRevisionId");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRuleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<double>("Hysteresis")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThresholdHigh")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier");

                    b.HasIndex("WorkspaceId", "MetricDefinitionId");

                    b.HasIndex("WorkspaceId", "RuleId", "Version")
                        .IsUnique();

                    b.ToTable("alert_rule_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_alert_revision_parameters", "\"DurationSeconds\" >= 0 AND \"CooldownSeconds\" >= 0 AND \"ExpectedIntervalSeconds\" > 0 AND \"Hysteresis\" >= 0 AND \"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRuleState", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ActiveEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FirstViolationAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("LastBooleanValue")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastIngestionRecordId")
                        .HasColumnType("uuid");

                    b.Property<double?>("LastNumericValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastTriggeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkspaceId", "RuleId", "DeviceIdentifier");

                    b.HasIndex("WorkspaceId", "DeviceIdentifier");

                    b.HasIndex("WorkspaceId", "RuleId", "RevisionId");

                    b.HasIndex("WorkspaceId", "RuleId", "DeviceIdentifier", "ActiveEventId");

                    b.ToTable("alert_rule_states", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastContactAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTelemetryOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastTelemetryPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastTelemetryReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastTelemetrySequence")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastContactAtUtc");

                    b.HasIndex("WorkspaceId", "Identifier");

                    b.HasIndex("TenantId", "WorkspaceId", "Identifier")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.DeviceCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UX_device_credentials_device_active")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("device_credentials", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.MetricDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ExpectedIntervalSec")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlertable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQueryable")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxExpectedValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("MinExpectedValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SemanticType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "MetricKey")
                        .IsUnique();

                    b.ToTable("metric_definitions", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.MetricDefinitionDiscoveryAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IngestionRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRecordId");

                    b.HasIndex("WorkspaceId", "DeviceId", "DiscoveredAtUtc");

                    b.ToTable("metric_definition_discovery_audits", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("platform_users", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryIngestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Battery")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("UptimeSec")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("TenantId");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.HasIndex("TenantId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "DeviceId");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "OccurredAtUtc")
                        .HasDatabaseName("IX_tir_tenant_workspace_device_occurred_at");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_telemetry_ingestion_records_tenant_workspace_device_sequence")
                        .HasFilter("\"Sequence\" IS NOT NULL");

                    b.ToTable("telemetry_ingestion_records", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryIngestionRejectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("LastReprocessAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PayloadRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReprocessAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("Reprocessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SourceRejectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ErrorType");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SourceRejectionId", "Reprocessed", "ErrorType", "ReceivedAtUtc")
                        .HasDatabaseName("IX_tirj_reprocess_eligibility");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "ReceivedAtUtc")
                        .HasDatabaseName("IX_tirj_tenant_workspace_device_received_at");

                    b.ToTable("telemetry_ingestion_rejections", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryPoint", b =>
                {
                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("IngestionRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("OccurredAtUtc", "Id");

                    b.HasIndex("IngestionRecordId");

                    b.HasIndex("MetricDefinitionId");

                    b.HasIndex("WorkspaceId", "DeviceId", "MetricDefinitionId", "OccurredAtUtc");

                    b.ToTable("telemetry_points", null, t =>
                        {
                            t.HasCheckConstraint("CK_telemetry_points_exactly_one_value", "((\"NumericValue\" IS NOT NULL)::int + (\"BooleanValue\" IS NOT NULL)::int + (\"TextValue\" IS NOT NULL)::int) = 1");
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.ToTable("telemetry_records", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("workspace_memberships", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertAcknowledgement", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertEvent", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "EventId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertDeliveryIntent", b =>
                {
                    b.HasOne("Fluxo.Domain.Alerts.AlertEventTransition", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "TransitionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvaluationAttempt", b =>
                {
                    b.HasOne("Fluxo.Domain.Alerts.AlertRuleRevision", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RuleId", "RevisionId")
                        .HasPrincipalKey("WorkspaceId", "RuleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertEvaluationWorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier", "QueueOrder", "WorkItemId")
                        .HasPrincipalKey("WorkspaceId", "DeviceIdentifier", "QueueOrder", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvaluationWorkItem", b =>
                {
                    b.HasOne("Fluxo.Domain.Alerts.AlertDeviceCoordination", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.TelemetryIngestionRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier", "IngestionRecordId")
                        .HasPrincipalKey("WorkspaceId", "DeviceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEvent", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier")
                        .HasPrincipalKey("WorkspaceId", "Identifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertRuleRevision", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RuleId", "RevisionId")
                        .HasPrincipalKey("WorkspaceId", "RuleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertEventTransition", b =>
                {
                    b.HasOne("Fluxo.Domain.Alerts.AlertEvent", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "EventId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.TelemetryIngestionRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "IngestionRecordId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRule", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertRuleRevision", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "Id", "CurrentRevisionId")
                        .HasPrincipalKey("WorkspaceId", "RuleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRuleRevision", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier")
                        .HasPrincipalKey("WorkspaceId", "Identifier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fluxo.Domain.Entities.MetricDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MetricDefinitionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RuleId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Alerts.AlertRuleState", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "DeviceIdentifier")
                        .HasPrincipalKey("WorkspaceId", "Identifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertRuleRevision", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RuleId", "RevisionId")
                        .HasPrincipalKey("WorkspaceId", "RuleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Alerts.AlertEvent", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RuleId", "DeviceIdentifier", "ActiveEventId")
                        .HasPrincipalKey("WorkspaceId", "RuleId", "DeviceIdentifier", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.DeviceCredential", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.MetricDefinitionDiscoveryAudit", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.TelemetryIngestionRecord", null)
                        .WithMany()
                        .HasForeignKey("IngestionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryPoint", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.TelemetryIngestionRecord", null)
                        .WithMany()
                        .HasForeignKey("IngestionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.MetricDefinition", null)
                        .WithMany()
                        .HasForeignKey("MetricDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.WorkspaceMembership", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
