// <auto-generated />
using System;
using Fluxo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluxo.Infrastructure.Migrations
{
    [DbContext(typeof(FluxoDbContext))]
    partial class FluxoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluxo.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Identifier")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryIngestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Battery")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("UptimeSec")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("TenantId");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.HasIndex("TenantId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "DeviceId");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "OccurredAtUtc")
                        .HasDatabaseName("IX_tir_tenant_workspace_device_occurred_at");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_telemetry_ingestion_records_tenant_workspace_device_sequence")
                        .HasFilter("\"Sequence\" IS NOT NULL");

                    b.ToTable("telemetry_ingestion_records", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryIngestionRejectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PayloadRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ErrorType");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("TenantId", "WorkspaceId", "DeviceId", "ReceivedAtUtc")
                        .HasDatabaseName("IX_tirj_tenant_workspace_device_received_at");

                    b.ToTable("telemetry_ingestion_rejections", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.ToTable("telemetry_records", (string)null);
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
